### ISSUE TITLE
Please implement part deletion

### ISSUE THREAD

**Issue by fat-lobyte** [my-th-os/KML#3]
Hi, first of all thanks for your amazing Tool! It is very helpful in various situations.

However, for me, it would be even more helpful if part deletion were a thing. Is it possible to implement that?
What would be needed to do that? In your forum post, you mentioned:

> parts (need to rebuild index numbers and attachments)

What exactly does this refer to? I understand the index numbers, but what do you mean about the attachments?
Also, could there be other issues that could arise from part deletion?

I might be able to help here, but I am unfamiliar with your code (although it looks very very clean, congrats on that ;) )

**Comment by my-th-os** [comment]
First restricted version of part deletion I had in mind would only allow deletion of parts that aren't parent of any other part, otherwise we would need to rebuild the parent-tree also. This would usually mean just deleting "outer" parts as seen from the root part. 
I'm not sure if I would like to enable a delete menu on some part and after clicking give a message "by the way if you delete this it will automatically delete all these 20 other parts in the chain afterwards... continue?"

What is to do for part deletion
- there are part attributes to change I know of
  - anything having "srfN = text, 10" or "attN = text, 10" would go to "..., 9" if part 5 is deleted
  - also "parent = 10" would need to change to "parent = 9"
  - these describe the attachments of parts to other parts
- there are attributes I don't know of or have forgotten :-)
- then the internal structure for the representation within KML has to be updated
  - the part indices "PART [xx] (...)" are just made by KML from the order they are coming in savefile
  - but these indices are used by KSP (seen above)
  - savefile attachments are sometimes uni- and some times bidirectional
  - KML stores everything bidirectional
  - all this could be worked around by just changing attributes and then reload the whole file
  - but we want deletion to react instantanious and atomic

This is a feature I also would like to add soon. Together with some copy&paste funtionality. But sadly I had little time for quite a while now. But I'm still with KSP and with KML. Any contribution would be welcome.

**Comment by fat-lobyte** [comment]
Thank you for your answer! I think your writup is a good starting point.
I also don'T have much time, but maybe I could try to take a look and see if I can help you implement this feature.

**Comment by my-th-os** [comment]
I enabled the menu item for the preconditions I had in mind. And then a not implemented message will pop up. It's not even in the preview build yet. 
One place to do work will be where the message pops up. The cleanup to avoid a forced reload of everything may go elsewhere, I'm not sure. 
Maybe I go on in the next days, maybe not.

**Comment by my-th-os** [comment]
I implemented part deletion like I had in mind. It's in the preview build now. Is there a need for more enhancements? 
I almost disassembled one vessel step by step having a view ingame after each step. May you do some further testing?

To share some new knowledge:
- there are attributes I don't know of or have forgotten
  - the symmetry attributes "sym" point to other part indices made in symmetry with this part
  - having this broken caused my KSP (still on 1.1.3) to slow down or ignoring further F9 hits
  - broken also means an emtpy value or -1 in this case
  - as this is a savegame killer I added a sanity check for this

**Comment by fat-lobyte** [comment]
For some reason, my Antivius (Windows Defender) won't let me download your ZIP file :(

Having done some limited testing, I think this works pretty well!

Good job on the implementation, this feature makes KML much more useful :)

**Comment by my-th-os** [comment]
Same problem on my side. Also same problem after recompile and reupload. No problem scanning the zip before upload. Strange. 

This is the virustotal analysis of my local zip:
https://www.virustotal.com/de/file/afe2c1aba0dd570749712eef884e3657cc8e2eac28c8d24dba6c7fbd76679980/analysis/1502643887/

Hand here from GitHub:
https://www.virustotal.com/de/url/63770f685612658e0c5d2aa876cb83d0703e190f96f02f47107fbccf68b90f4a/analysis/1502644132/ (see downloaded file)

That doesn't report any problem, Microsoft included. Even stranger.

Need to change something to avoid this false positive.
Higher compression rate to have the zip content changed, same problem.
Compiled without optimization to have the exe changed, same problem.
Or maybe my results are bad due to browser cache.
No further ideas. Need to test again after the code really changed or that stupid virus signatures are updated.
